# Generated by Django 5.1.1 on 2024-10-02 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=10)),
                ('faculty_mentor', models.CharField(blank=True, max_length=255, null=True)),
                ('be_student_mentor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('roll_number', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=1)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rollno', models.CharField(max_length=100, unique=True)),
                ('atte_ise1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('atte_mse', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attendance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cts', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ise1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mse', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('semcgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('counseling_dates', models.TextField(blank=True, null=True)),
                ('question1', models.TextField(blank=True, null=True)),
                ('question2', models.TextField(blank=True, null=True)),
                ('question3', models.TextField(blank=True, null=True)),
                ('question4', models.TextField(blank=True, null=True)),
                ('question5', models.TextField(blank=True, null=True)),
                ('question6', models.TextField(blank=True, null=True)),
                ('question7', models.TextField(blank=True, null=True)),
                ('question8', models.TextField(blank=True, null=True)),
                ('question9', models.TextField(blank=True, null=True)),
                ('question10', models.TextField(blank=True, null=True)),
                ('question11', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
