# Generated by Django 5.1.1 on 2024-10-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_studentform_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='mentor',
            field=models.CharField(max_length=255),
        ),
    ]
