# Generated by Django 5.1.1 on 2024-10-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_alter_studentform_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='mentor',
            new_name='mentor_name',
        ),
    ]
