# Generated by Django 5.1.1 on 2024-10-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_rename_mentor_studentform_mentor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='question12',
            field=models.TextField(blank=True, null=True),
        ),
    ]
