# Generated by Django 5.1.1 on 2024-10-03 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_studentform_question12'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='cts',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='question10',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='question11',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='question12',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='question8',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='question9',
        ),
    ]
