# Generated by Django 5.1.1 on 2024-10-03 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0006_remove_studentform_cts_remove_studentform_question10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFollowup_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rollno', models.CharField(max_length=100, unique=True)),
                ('mentor_name', models.CharField(max_length=255)),
                ('atte_ise1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('atte_mse', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attendance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ise1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mse', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('semcgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('counseling_dates', models.TextField(blank=True, null=True)),
                ('question1', models.TextField(blank=True, null=True)),
                ('question2', models.TextField(blank=True, null=True)),
                ('question3', models.TextField(blank=True, null=True)),
                ('question4', models.TextField(blank=True, null=True)),
                ('question5', models.TextField(blank=True, null=True)),
                ('question6', models.TextField(blank=True, null=True)),
                ('question7', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='studentform',
            name='cts',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='question9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
