# Generated by Django 5.1.1 on 2024-10-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0007_studentfollowup_form_studentform_cts_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentFollowup_Form',
            new_name='StudentFollowupForm',
        ),
    ]
