# Generated by Django 5.1.1 on 2024-10-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0010_remove_studentform_challenges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='Challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='Opportunities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='Strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='Weakness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='ao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentform',
            name='nao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
