# Generated by Django 5.1.1 on 2024-10-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0013_studentform_challenges_studentform_opportunities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfollowupform',
            name='ao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfollowupform',
            name='nao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
